server:
  port: 8080

azure:
  openai:
    endpoint: ${AZURE_OPENAI_ENDPOINT}
    deployment: ${AZURE_OPENAI_DEPLOYMENT:gpt-4o-mini-tts}
    model: ${AZURE_OPENAI_MODEL:gpt-4o-mini-tts}

logging:
  level:
    com.ttsapp: INFO
    org.springframework.web: INFO

spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
