server:
  port: ${SERVER_PORT:8080}

azure:
  openai:
    endpoint: ${AZURE_OPENAI_ENDPOINT:https://ropreddy-5282-resource.cognitiveservices.azure.com}
    deployment: ${AZURE_OPENAI_DEPLOYMENT:gpt-4o-mini-tts}
    model: ${AZURE_OPENAI_MODEL:gpt-4o-mini-tts}
    api-key: ${AZURE_OPENAI_API_KEY}

logging:
  level:
    com.ttsapp: ${LOG_LEVEL:INFO}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}

spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
