server:
  port: ${SERVER_PORT:8080}

azure:
  openai:
    endpoint: ${AZURE_OPENAI_ENDPOINT}
    deployment: ${AZURE_OPENAI_DEPLOYMENT:gpt-audio}
    model: ${AZURE_OPENAI_MODEL:gpt-audio}

logging:
  level:
    com.ttsapp: ${LOG_LEVEL:INFO}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}

spring:
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0

# Rate limiting configuration
app:
  rate-limit:
    max-requests-per-minute: ${RATE_LIMIT_REQUESTS_PER_MINUTE:10}
    max-requests-per-hour: ${RATE_LIMIT_REQUESTS_PER_HOUR:100}
    max-characters-per-hour: ${RATE_LIMIT_CHARACTERS_PER_HOUR:50000}
    enabled: ${RATE_LIMIT_ENABLED:true}
